"""empty message

Revision ID: 24056d9b0abd
Revises: 441b04b83e20
Create Date: 2020-02-22 20:33:50.833455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24056d9b0abd'
down_revision = '441b04b83e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('message', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('message', 'date')
    # ### end Alembic commands ###
