"""empty message

Revision ID: 2e09ab5a1490
Revises: d2fe341180a2
Create Date: 2020-01-29 14:28:08.196612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e09ab5a1490'
down_revision = 'd2fe341180a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bg', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('img', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    op.drop_column('user', 'bg')
    # ### end Alembic commands ###
