"""empty message

Revision ID: 2fe73cde4473
Revises: e9acb788de91
Create Date: 2020-01-29 14:52:32.924691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe73cde4473'
down_revision = 'e9acb788de91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
