"""empty message

Revision ID: 5bbfaabbd4f7
Revises: 2fe73cde4473
Create Date: 2020-01-29 14:56:50.938979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbfaabbd4f7'
down_revision = '2fe73cde4473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
