"""empty message

Revision ID: 7e156c62b2d7
Revises: 84185eb4cc66
Create Date: 2020-02-18 20:25:54.673341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e156c62b2d7'
down_revision = '84185eb4cc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
