"""empty message

Revision ID: 84185eb4cc66
Revises: 11df15e958c4
Create Date: 2020-02-18 20:18:40.798731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84185eb4cc66'
down_revision = '11df15e958c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
