"""empty message

Revision ID: 96e0aa576018
Revises: e344a0422a73
Create Date: 2020-02-04 17:21:31.928878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e0aa576018'
down_revision = 'e344a0422a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'read')
    # ### end Alembic commands ###
