"""empty message

Revision ID: ce0b7b411fc2
Revises: d46fd374d5ed
Create Date: 2020-02-27 12:46:06.866017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b7b411fc2'
down_revision = 'd46fd374d5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text1', sa.Text(), nullable=False))
    op.drop_column('message', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('message', 'text1')
    # ### end Alembic commands ###
