"""empty message

Revision ID: e344a0422a73
Revises: 5bbfaabbd4f7
Create Date: 2020-01-30 18:28:28.704539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e344a0422a73'
down_revision = '5bbfaabbd4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('data', sa.DateTime(), nullable=False))
    op.add_column('message', sa.Column('user_from_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('user_to_id', sa.Integer(), nullable=False))
    op.drop_constraint('message_user_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_to_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['user_from_id'], ['id'])
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_id_fkey', 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'user_to_id')
    op.drop_column('message', 'user_from_id')
    op.drop_column('message', 'data')
    # ### end Alembic commands ###
