"""empty message

Revision ID: e9acb788de91
Revises: 2e09ab5a1490
Create Date: 2020-01-29 14:44:40.173222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9acb788de91'
down_revision = '2e09ab5a1490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'img',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'bg',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
