version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - env_file
    ports:
      - "5432:5432"
  flaskapp:
    tty: true
    build:
      context: ./app/
    env_file:
      - env_file
    ports:
      - "5000:5000"
    volumes:
      - "./app:/home/meow"
    depends_on:
      - db
volumes:
  dbdata: